### ISSUE TITLE
Typehint Validator interfaces instead of a specific class

### ISSUE THREAD

**Issue by ajessu** [ChessCom/DiagramGenerator#6]
When trying to use the library standalone, two errors come up because of recent Symfony component validator changes, which is now returning a `LegacyValidator` instead of a `Validator`, depending on the version of Symfony the library runs in.

We are type hinting with classes [here](https://github.com/ChessCom/DiagramGenerator/blob/master/src/DiagramGenerator/ConfigLoader.php#L43) and [here](https://github.com/ChessCom/DiagramGenerator/blob/master/src/DiagramGenerator/Generator.php#L28), where we should be type hinting with an interface there: `Symfony\Component\Validator\Validator\ValidatorInterface`

Error can be reproduced by trying to run the library standalone with the following script, in the root of the library:

```php
<?php

use DiagramGenerator\Config;
use DiagramGenerator\Generator;
use DiagramGenerator\Fen;
use Doctrine\Common\Annotations\AnnotationRegistry;
use Symfony\Component\Validator\Validation;

$loader = require __DIR__ . '/vendor/autoload.php';
$loader->register(true);
AnnotationRegistry::registerLoader(array($loader, 'loadClass'));


$validator = Validation::createValidator();
$config = new Config();
$config
    ->setFen(Fen::DEFAULT_FEN)
    ->setSizeIndex(2);
$generator = new Generator($validator);
$image = $generator->buildDiagram($config);
var_dump($image);
```

**Comment by lackovic10** [comment]
https://github.com/ChessCom/DiagramGenerator/pull/16
